In [17]:
import pandas as pd 

PATHS = {
    'pop_2020': "/Users/romain/Desktop/Projets DS/Python-project/analyse/data/population_2020.CSV",
    'pop_2014': "/Users/romain/Desktop/Projets DS/Python-project/analyse/data/population_2014.xls",
    'diplo_2020': "/Users/romain/Desktop/Projets DS/Python-project/analyse/data/diplome_2020.CSV",
    'diplo_2014': "/Users/romain/Desktop/Projets DS/Python-project/analyse/data/diplome_2014.xls",
    'rev_2019': "/Users/romain/Desktop/Projets DS/Python-project/analyse/data/revenu_2019.csv",
    'rev_2013': "/Users/romain/Desktop/Projets DS/Python-project/analyse/data/revenu_2013.xls"
}

df_pop_2020 = pd.read_csv(PATHS['pop_2020'], sep=';',dtype={'COM':'str'})
df_pop_2014 = pd.read_excel(PATHS['pop_2014'],header=5,dtype={'COM':'str'})
df_diplo_2020 = pd.read_csv(PATHS['diplo_2020'], sep=';',header=0,dtype={'COM':'str'})
df_diplo_2014 = pd.read_excel(PATHS['diplo_2014'],header=5,dtype={'CODGEO':'str'})
df_rev_2019 = pd.read_csv(PATHS['rev_2019'], sep=';',dtype={'CODGEO':'str'})
df_rev_2013 = pd.read_excel(PATHS['rev_2013'],header=5,dtype={'CODGEO':'str'})

/var/folders/47/r5kv9z4j6kg1sk0dvr2l5ydh0000gn/T/ipykernel_50243/864678703.py:12: DtypeWarning: Columns (0,3) have mixed types. Specify dtype option on import or set low_memory=False.
  df_pop_2020 = pd.read_csv(PATHS['pop_2020'], sep=';',dtype={'COM':'str'})
/var/folders/47/r5kv9z4j6kg1sk0dvr2l5ydh0000gn/T/ipykernel_50243/864678703.py:14: DtypeWarning: Columns (0,3) have mixed types. Specify dtype option on import or set low_memory=False.
  df_diplo_2020 = pd.read_csv(PATHS['diplo_2020'], sep=';',header=0,dtype={'COM':'str'})

Fusion en un unqiue .csv de toutes les données explicatives brutes (sans delta). On fera deltaY=delta vote, sur les deltaX.

In [18]:
print("Pop 2014 unique ?", df_pop_2014['COM'].is_unique)
print("Pop 2020 unique ?", df_pop_2020['COM'].is_unique)
print("Diplo 2020 unique ?", df_diplo_2020['COM'].is_unique)
print("Diplo 2014 unique ?", df_diplo_2014['CODGEO'].is_unique)
print("Rev 2013 unique ?", df_rev_2013['CODGEO'].is_unique)
print("Rev 2019 unique ?", df_rev_2019['CODGEO'].is_unique)

Pop 2014 unique ? False
Pop 2020 unique ? False
Diplo 2020 unique ? False
Diplo 2014 unique ? True
Rev 2013 unique ? True
Rev 2019 unique ? True

In [20]:

df_pop_2020=df_pop_2020[['COM','P20_POP','C20_POP15P_CS3']]
df_pop_2014=df_pop_2014[['COM','P14_POP','C14_POP15P_CS3']]
df_pop_2020.head()
df_pop_2014.head()
df_diplo_2014=df_diplo_2014[['CODGEO','P14_NSCOL15P_SUP']]
df_diplo_2020=df_diplo_2020[['COM','P20_NSCOL15P_SUP2','P20_NSCOL15P_SUP34','P20_NSCOL15P_SUP5']]
df_rev_2013=df_rev_2013[['CODGEO','MED13']]
df_rev_2019=df_rev_2019[['CODGEO','MED19']]

In [29]:
print("Pop 2014 unique ?", df_pop_2014['COM'].is_unique)
print("Pop 2020 unique ?", df_pop_2020['COM'].is_unique)
print("Diplo 2020 unique ?", df_diplo_2020['COM'].is_unique)
print("Diplo 2014 unique ?", df_diplo_2014['CODGEO'].is_unique)
print("Rev 2013 unique ?", df_rev_2013['CODGEO'].is_unique)
print("Rev 2019 unique ?", df_rev_2019['CODGEO'].is_unique)

Pop 2014 unique ? True
Pop 2020 unique ? True
Diplo 2020 unique ? True
Diplo 2014 unique ? True
Rev 2013 unique ? True
Rev 2019 unique ? True

Problème de doublons (population par IRIS, même COM, ou alors Hommes vs Femmes...)
Solution: groupby

In [26]:
df_diplo_2020_test = df_diplo_2020.groupby('COM').sum().reset_index()

In [27]:
df_diplo_2020_test.head()

     COM  P20_NSCOL15P_SUP2  P20_NSCOL15P_SUP34  P20_NSCOL15P_SUP5
0  01001          83.435537           58.938581          38.706320
1  01002          28.977294           27.590460          23.934686
2  01004        1345.650547          800.138921         732.117886
3  01005         186.000000          104.000000          87.000000
4  01006          11.894737           10.903509           5.947368

.reset_index() INDISPENSABLE pour remettre l'index et remettre COm en nom de colonne pour jointure

In [28]:
df_diplo_2020 = df_diplo_2020.groupby('COM').sum().reset_index()
df_pop_2014 = df_pop_2014.groupby('COM').sum().reset_index()
df_pop_2020 = df_pop_2020.groupby('COM').sum().reset_index()

In [30]:
df_pop_2020.head()

     COM  P20_POP  C20_POP15P_CS3
0  01001    806.0       61.774238
1  01002    262.0       18.283656
2  01004  14288.0      804.651500
3  01005   1782.0      115.000000
4  01006    113.0        9.912281

In [31]:
df_2014=pd.merge(df_pop_2014,df_diplo_2014, left_on='COM', right_on='CODGEO', how='left')

In [32]:
df_2014.head()
df_2014 = df_2014.drop(columns=['CODGEO'])
#df_rev_2013.head()

In [33]:

df_2014=pd.merge(df_2014,df_rev_2013, left_on='COM', right_on='CODGEO', how='left')

In [34]:
df_2014=df_2014.drop(columns=['CODGEO'])

In [35]:
df_2014.head()

     COM  P14_POP  C14_POP15P_CS3  P14_NSCOL15P_SUP         MED13
0  01001    767.0       75.000000        141.000000  22130.000000
1  01002    239.0       14.753086         59.995885  23213.000000
2  01004  14022.0      743.288479       2326.327150  19554.000000
3  01005   1627.0      105.518839        281.383570  22387.619048
4  01006    109.0        4.954545         12.881818  21871.666667

In [77]:
df_rev_2019.head()

  CODGEO  MED19
0  01001  23970
1  01002  23640
2  01004  20510
3  01005  24050
4  01006      s

In [36]:
df_2020=pd.merge(df_pop_2020,df_diplo_2020, left_on='COM', right_on='COM', how='left')

In [37]:
df_2020.head()
df_2020=pd.merge(df_2020,df_rev_2019, left_on='COM', right_on='CODGEO', how='left')

In [38]:
df_2020.head()
df_2020=df_2020.drop(columns=['CODGEO'])

In [39]:
df_2020.head()

,COM,P20_POP,C20_POP15P_CS3,P20_NSCOL15P_SUP2,P20_NSCOL15P_SUP34,P20_NSCOL15P_SUP5,MED19
0,01001,806.0,61.774238,83.435537,58.938581,38.706320,23970
1,01002,262.0,18.283656,28.977294,27.590460,23.934686,23640
2,01004,14288.0,804.651500,1345.650547,800.138921,732.117886,20510
3,01005,1782.0,115.000000,186.000000,104.000000,87.000000,24050
4,01006,113.0,9.912281,11.894737,10.903509,5.947368,s

In [40]:
df=pd.merge(df_2014,df_2020, left_on='COM', right_on='COM', how='left')

In [41]:
df.head(100)

,COM,P14_POP,C14_POP15P_CS3,P14_NSCOL15P_SUP,MED13,P20_POP,C20_POP15P_CS3,P20_NSCOL15P_SUP2,P20_NSCOL15P_SUP34,P20_NSCOL15P_SUP5,MED19
0,01001,767.0,75.000000,141.000000,22130.000000,806.0,61.774238,83.435537,58.938581,38.706320,23970
1,01002,239.0,14.753086,59.995885,23213.000000,262.0,18.283656,28.977294,27.590460,23.934686,23640
2,01004,14022.0,743.288479,2326.327150,19554.000000,14288.0,804.651500,1345.650547,800.138921,732.117886,20510
3,01005,1627.0,105.518839,281.383570,22387.619048,1782.0,115.000000,186.000000,104.000000,87.000000,24050
4,01006,109.0,4.954545,12.881818,21871.666667,113.0,9.912281,11.894737,10.903509,5.947368,s
...,...,...,...,...,...,...,...,...,...,...,...
95,01103,1459.0,193.000000,449.000000,36382.000000,2226.0,335.743069,187.194660,227.757010,324.653800,40750
96,01104,461.0,10.021739,95.206522,22047.200000,453.0,32.190995,49.036584,38.875977,30.720273,25530
97,01105,1489.0,170.000000,347.000000,25740.400000,1867.0,204.156572,232.720261,150.055711,154.126633,27000
98,01106,173.0,5.000000,24.000000,19107.500000,178.0,4.972067,15.910615,8.949721,3.977654,22170
99,01107,136.0,10.074074,31.229630,21548.000000,136.0,18.888889,11.333333,17.944444,7.555556,22050

In [42]:
# Chemin de sortie
output_path = '/Users/romain/Desktop/Projets DS/Python-project/analyse/fusion_data.csv'

# L'exportation propre
df.to_csv(
    output_path, 
    index=False,   # CRUCIAL : Ne pas enregistrer la colonne d'index (0, 1, 2...)
    na_rep='NA',   # CRUCIAL POUR R : Remplacer les vides par "NA"
    sep=',',       # Standard international (virgule)
    encoding='utf-8'
)

print(f"Exporté avec succès vers : {output_path}")

Exporté avec succès vers : /Users/romain/Desktop/Projets DS/Python-project/analyse/fusion_data.csv

In [43]:
import pandas as pd 

df_elec_2014 = pd.read_csv('/Users/romain/Desktop/Projets DS/Python-project/elec_2014.csv', dtype={'Code commune':'str'})
df_elec_2020 = pd.read_csv('/Users/romain/Desktop/Projets DS/Python-project/elec_2020.csv', dtype={'Code commune':'str'})

df_elec_2014 = df_elec_2014.rename(columns={'Code commune':'COM','D_elec_2020':'D_elec_2014','Code Nuance':'Code Nuance 2014','% Voix/Exp':'% Voix/Exp 2014'})
df_elec_2020 = df_elec_2020.rename(columns={'Code commune':'COM','Code Nuance':'Code Nuance 2020','% Voix/Exp':'% Voix/Exp 2020'})

In [44]:
df_elec_2020.head()

,COM,Libellé de la commune,N.Pan.,Code Nuance 2020,Sexe,Nom,Prénom,Liste,Sièges / Elu,Sièges Secteur,Sièges CC,Voix,% Voix/Ins,% Voix/Exp 2020,D_elec_2020
0,01034,Belley,4.0,LDVD,M,LAHUERTA,Dimitri,AGIR POUR BELLEY ET BUGEY SUD,23.0,0.0,12.0,1525.0,26.49,54.99,0.0
1,01160,Ferney-Voltaire,2.0,LDVD,M,RAPHOZ,Daniel,Ferney-Voltaire Valeurs Communes,23.0,0.0,5.0,747.0,19.67,50.40,0.0
2,01194,Jassans-Riottier,4.0,LDVD,M,REVERCHON,Jean-Pierre,JASSANS LA FORCE D'AGIR ENSEMBLE,23.0,0.0,5.0,856.0,19.65,52.16,0.0
3,01249,Miribel,1.0,LDVD,M,GAITET,Jean-Pierre,"Miribel pour tous, Miribel à tous",23.0,0.0,11.0,1391.0,20.32,50.73,0.0
4,01354,Saint-Genis-Pouilly,2.0,LDVG,M,BERTRAND,Hubert,"SAINT-GENIS-POUILLY, C'EST VOUS",25.0,0.0,5.0,867.0,17.29,46.12,1.0

In [45]:

df_elec_2014 = df_elec_2014[ ['COM','Code Nuance 2014','D_elec_2014','% Voix/Exp 2014'] ]
df_elec_2020 = df_elec_2020[ ['COM','Code Nuance 2020','D_elec_2020','% Voix/Exp 2020'] ]

In [47]:
df_elec_2014.head()

     COM Code Nuance 2014  D_elec_2014  % Voix/Exp 2014
0  01004             LDVD          0.0            61.31
1  01007             LDVG          1.0            46.78
2  01034             LDVD          0.0            51.17
3  01160             LDVD          0.0            50.45
4  01185             LUDI          0.0            61.28

In [48]:
df_variables = pd.read_csv("/Users/romain/Desktop/Projets DS/Python-project/analyse/fusion_data.csv", dtype={'COM':'str'})
df_variables.head()

,COM,P14_POP,C14_POP15P_CS3,P14_NSCOL15P_SUP,MED13,P20_POP,C20_POP15P_CS3,P20_NSCOL15P_SUP2,P20_NSCOL15P_SUP34,P20_NSCOL15P_SUP5,MED19
0,01001,767.0,75.000000,141.000000,22130.000000,806.0,61.774238,83.435537,58.938581,38.706320,23970
1,01002,239.0,14.753086,59.995885,23213.000000,262.0,18.283656,28.977294,27.590460,23.934686,23640
2,01004,14022.0,743.288479,2326.327150,19554.000000,14288.0,804.651500,1345.650547,800.138921,732.117886,20510
3,01005,1627.0,105.518839,281.383570,22387.619048,1782.0,115.000000,186.000000,104.000000,87.000000,24050
4,01006,109.0,4.954545,12.881818,21871.666667,113.0,9.912281,11.894737,10.903509,5.947368,s

In [49]:
df_final=pd.merge(df_variables,df_elec_2014, left_on='COM', right_on='COM', how='left')

In [50]:
df_final.head()

,COM,P14_POP,C14_POP15P_CS3,P14_NSCOL15P_SUP,MED13,P20_POP,C20_POP15P_CS3,P20_NSCOL15P_SUP2,P20_NSCOL15P_SUP34,P20_NSCOL15P_SUP5,MED19,Code Nuance 2014,D_elec_2014,% Voix/Exp 2014
0,01001,767.0,75.000000,141.000000,22130.000000,806.0,61.774238,83.435537,58.938581,38.706320,23970,NaN,NaN,NaN
1,01002,239.0,14.753086,59.995885,23213.000000,262.0,18.283656,28.977294,27.590460,23.934686,23640,NaN,NaN,NaN
2,01004,14022.0,743.288479,2326.327150,19554.000000,14288.0,804.651500,1345.650547,800.138921,732.117886,20510,LDVD,0.0,61.31
3,01005,1627.0,105.518839,281.383570,22387.619048,1782.0,115.000000,186.000000,104.000000,87.000000,24050,NaN,NaN,NaN
4,01006,109.0,4.954545,12.881818,21871.666667,113.0,9.912281,11.894737,10.903509,5.947368,s,NaN,NaN,NaN

In [51]:
df_final=pd.merge(df_final,df_elec_2020, left_on='COM', right_on='COM', how='left')
df_final.head()

,COM,P14_POP,C14_POP15P_CS3,P14_NSCOL15P_SUP,MED13,P20_POP,C20_POP15P_CS3,P20_NSCOL15P_SUP2,P20_NSCOL15P_SUP34,P20_NSCOL15P_SUP5,MED19,Code Nuance 2014,D_elec_2014,% Voix/Exp 2014,Code Nuance 2020,D_elec_2020,% Voix/Exp 2020
0,01001,767.0,75.000000,141.000000,22130.000000,806.0,61.774238,83.435537,58.938581,38.706320,23970,NaN,NaN,NaN,NaN,NaN,NaN
1,01002,239.0,14.753086,59.995885,23213.000000,262.0,18.283656,28.977294,27.590460,23.934686,23640,NaN,NaN,NaN,NaN,NaN,NaN
2,01004,14022.0,743.288479,2326.327150,19554.000000,14288.0,804.651500,1345.650547,800.138921,732.117886,20510,LDVD,0.0,61.31,NaN,NaN,NaN
3,01005,1627.0,105.518839,281.383570,22387.619048,1782.0,115.000000,186.000000,104.000000,87.000000,24050,NaN,NaN,NaN,NaN,NaN,NaN
4,01006,109.0,4.954545,12.881818,21871.666667,113.0,9.912281,11.894737,10.903509,5.947368,s,NaN,NaN,NaN,NaN,NaN,NaN

In [52]:
df_final.head(10)

,COM,P14_POP,C14_POP15P_CS3,P14_NSCOL15P_SUP,MED13,P20_POP,C20_POP15P_CS3,P20_NSCOL15P_SUP2,P20_NSCOL15P_SUP34,P20_NSCOL15P_SUP5,MED19,Code Nuance 2014,D_elec_2014,% Voix/Exp 2014,Code Nuance 2020,D_elec_2020,% Voix/Exp 2020
0,01001,767.0,75.000000,141.000000,22130.000000,806.0,61.774238,83.435537,58.938581,38.706320,23970,NaN,NaN,NaN,NaN,NaN,NaN
1,01002,239.0,14.753086,59.995885,23213.000000,262.0,18.283656,28.977294,27.590460,23.934686,23640,NaN,NaN,NaN,NaN,NaN,NaN
2,01004,14022.0,743.288479,2326.327150,19554.000000,14288.0,804.651500,1345.650547,800.138921,732.117886,20510,LDVD,0.0,61.31,NaN,NaN,NaN
3,01005,1627.0,105.518839,281.383570,22387.619048,1782.0,115.000000,186.000000,104.000000,87.000000,24050,NaN,NaN,NaN,NaN,NaN,NaN
4,01006,109.0,4.954545,12.881818,21871.666667,113.0,9.912281,11.894737,10.903509,5.947368,s,NaN,NaN,NaN,NaN,NaN,NaN
5,01007,2570.0,195.000000,497.000000,21650.666667,2827.0,211.204367,291.197842,180.816511,149.356733,23380,LDVG,1.0,46.78,NaN,NaN,NaN
6,01008,743.0,71.903226,157.787634,23669.523810,768.0,50.394579,91.623804,43.816990,39.516518,25450,NaN,NaN,NaN,NaN,NaN,NaN
7,01009,338.0,16.047478,65.192878,21486.250000,324.0,4.773479,31.017988,23.239624,21.325734,23790,NaN,NaN,NaN,NaN,NaN,NaN
8,01010,1142.0,42.731525,129.262862,21015.333333,1101.0,44.135561,74.904925,45.561073,28.051864,23770,NaN,NaN,NaN,NaN,NaN,NaN
9,01011,397.0,70.119481,83.524675,22690.000000,368.0,34.615852,38.199701,29.418770,15.809406,24450,NaN,NaN,NaN,NaN,NaN,NaN

Analyse des données fusionnées (NaN, 0, 1...)

In [53]:
comptage2020 = df_final['D_elec_2020'].value_counts(dropna=False)
print(comptage2020)
comptage2014 = df_final['D_elec_2014'].value_counts(dropna=False)
print(comptage2014)

D_elec_2020
NaN    34610
0.0     1006
1.0      294
Name: count, dtype: int64
D_elec_2014
NaN    34279
0.0     1099
1.0      532
Name: count, dtype: int64

In [54]:
df_clean = df_final.dropna(subset=['D_elec_2014', 'D_elec_2020'])

In [58]:
print(df_clean.columns)

Index(['COM', 'P14_POP', 'part_cadres_2014', 'P14_NSCOL15P_SUP', 'MED13',
       'P20_POP', 'part_cadres_2020', 'P20_NSCOL15P_SUP2',
       'P20_NSCOL15P_SUP34', 'P20_NSCOL15P_SUP5', 'MED19', 'Code Nuance 2014',
       'D_elec_2014', '% Voix/Exp 2014', 'Code Nuance 2020', 'D_elec_2020',
       '% Voix/Exp 2020'],
      dtype='object')

In [65]:
print(df_clean.head())
df_clean=df_clean.rename(columns={'part_cadres_2014':'cadres_2014','part_cadres_2020':'cadres_2020'})

        COM  pop2014  cadres_2014  P14_NSCOL15P_SUP         MED13  pop2020  \
30    01034   8983.0   338.455942       1498.801418  18549.000000   9207.0
146   01160   9337.0  1498.179206       3348.661633  25508.333333  10612.0
174   01194   6222.0   343.211268       1033.799267  21018.461538   6337.0
223   01249   9425.0   861.382083       2141.765868  22710.666667  10202.0
1215  03001   2847.0   151.938556        485.223131  20327.500000   2899.0

      cadres_2020  P20_NSCOL15P_SUP2  P20_NSCOL15P_SUP34  P20_NSCOL15P_SUP5  \
30     355.820237         711.274174          542.927266         487.613155
146   1426.479025         617.862569         1129.906809        2210.238825
174    385.000000         538.000000          390.000000         339.000000
223   1180.000000         920.000000          792.000000        1001.000000
1215   150.000000         264.000000          192.000000         137.000000

      ... D_elec_2014 pct_voix_exp_2014  Code Nuance 2020  D_elec_2020  \
30    ...         0.0             51.17              LDVD          0.0
146   ...         0.0             50.45              LDVD          0.0
174   ...         0.0             56.77              LDVD          0.0
223   ...         1.0             48.11              LDVD          0.0
1215  ...         1.0             42.87               LNC          0.0

     pct_voix_exp_2020  total_diplome_2020  delta_elec  delta_pop  \
30               54.99         1741.814595         0.0      224.0
146              50.40         3958.008204         0.0     1275.0
174              52.16         1267.000000         0.0      115.0
223              50.73         2713.000000        -1.0      777.0
1215             57.23          593.000000        -1.0       52.0

      part_diplome_14  part_diplome_20
30           0.166849         0.189184
146          0.358644         0.372975
174          0.166152         0.199937
223          0.227243         0.265928
1215         0.170433         0.204553

[5 rows x 22 columns]

In [72]:
# creation des variables delta 

# On reconstruit le total "Supérieur" pour 2020 (somme des 3 colonnes)
df_clean['total_diplome_2020'] = (
    df_clean['P20_NSCOL15P_SUP2'] + 
    df_clean['P20_NSCOL15P_SUP34'] + 
    df_clean['P20_NSCOL15P_SUP5']
)

df_clean=df_clean.rename(columns={'P14_POP':'pop2014','P20_POP':'pop2020','% Voix/Exp 2014':'pct_voix_exp_2014','% Voix/Exp 2020':'pct_voix_exp_2020'})

# Delta Vote (Variable Y) : -1 (Perdu), 0 (Stable), +1 (Gagné)
df_clean['delta_elec'] = df_clean['D_elec_2020'] - df_clean['D_elec_2014']


# Delta Population 
df_clean['delta_pop'] = df_clean['pop2020'] - df_clean['pop2014']

# Delta Diplômés en %

df_clean['part_diplome_14'] = df_clean['P14_NSCOL15P_SUP'] / df_clean['pop2014']
df_clean['part_diplome_20'] = df_clean['total_diplome_2020'] / df_clean['pop2020']

# Delta Cadres en %

df_clean['part_cadres_2014'] = df_clean['cadres_2014'] / df_clean['pop2014']
df_clean['part_cadres_2020'] = df_clean['cadres_2020'] / df_clean['pop2020']

df_clean['delta_pct_diplome'] = df_clean['part_diplome_20'] - df_clean['part_diplome_14']


# Souvent, on prend le stock initial (2013) pour voir si "être riche au début" prédit le changement.

cols_utiles = [
    'COM',           # ID
    'delta_elec', 
    'D_elec_2014',
    'D_elec_2020',
    'pct_voix_exp_2014',
    'pct_voix_exp_2020',
    'Code Nuance 2014',
    'Code Nuance 2020',
    'part_diplome_14',
    'part_diplome_20',
    'delta_pct_diplome',
    'part_cadres_2014',
    'part_cadres_2020',
          'pop2014',
    'pop2020',
    'delta_pop',     # X1
     # X2
    'MED13', # X3
              'MED19'        # X4  
]

df_regression = df_clean[cols_utiles].copy()

# Aperçu
print(df_regression.head())

        COM  delta_elec  D_elec_2014  D_elec_2020  pct_voix_exp_2014  \
30    01034         0.0          0.0          0.0              51.17
146   01160         0.0          0.0          0.0              50.45
174   01194         0.0          0.0          0.0              56.77
223   01249        -1.0          1.0          0.0              48.11
1215  03001        -1.0          1.0          0.0              42.87

      pct_voix_exp_2020 Code Nuance 2014 Code Nuance 2020  part_diplome_14  \
30                54.99             LDVD             LDVD         0.166849
146               50.40             LDVD             LDVD         0.358644
174               52.16             LDIV             LDVD         0.166152
223               50.73             LDVG             LDVD         0.227243
1215              57.23             LDVG              LNC         0.170433

      part_diplome_20  delta_pct_diplome  part_cadres_2014  part_cadres_2020  \
30           0.189184           0.022335          0.037677          0.038647
146          0.372975           0.014330          0.160456          0.134421
174          0.199937           0.033785          0.055161          0.060754
223          0.265928           0.038685          0.091393          0.115664
1215         0.204553           0.034120          0.053368          0.051742

      pop2014  pop2020  delta_pop         MED13  MED19
30     8983.0   9207.0      224.0  18549.000000  20030
146    9337.0  10612.0     1275.0  25508.333333  26770
174    6222.0   6337.0      115.0  21018.461538  22840
223    9425.0  10202.0      777.0  22710.666667  24860
1215   2847.0   2899.0       52.0  20327.500000  21810

In [73]:
# Chemin de sortie
output_path = '/Users/romain/Desktop/Projets DS/Python-project/analyse/data_pour_regression.csv'

# L'exportation propre
df_regression.to_csv(
    output_path, 
    index=False,   # CRUCIAL : Ne pas enregistrer la colonne d'index (0, 1, 2...)
    na_rep='NA',   # CRUCIAL POUR R : Remplacer les vides par "NA"
    sep=',',       # Standard international (virgule)
    encoding='utf-8'
)

print(f"Exporté avec succès vers : {output_path}")

Exporté avec succès vers : /Users/romain/Desktop/Projets DS/Python-project/analyse/data_pour_regression.csv